apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-frontend
  namespace: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-frontend
  template:
    metadata:
      labels:
        app: healthcare-frontend
    spec:
      containers:
        - name: frontend
          image: <REGISTRY>/healthcare-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-frontend
  namespace: healthcare
spec:
  selector:
    app: healthcare-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
